[package]
name = "yield"
version = "1.0.0"
authors = ["arjanjohan"]

[addresses]
lottery_addr="a990e02c32e468dd942653c48ee53d0af6ae27ea2c17b790621d8deb1f300dd4"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
