[package]
name = "lottery"
version = "1.0.0"
authors = ["arjanjohan"]

[addresses]
lottery_addr="0x0a4c57880adc5121256de0d2822b25a27974d63d08d5212415472acd7bdd24eb"
yield_addr="0x07261beac6e023ed2ba91de8e784c4ae66ef008e62c6ffd989410a7d344fa776"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.yield]
local = "../yield"

[dev-dependencies]
