[package]
name = "lottery"
version = "1.0.0"
authors = ["arjanjohan"]

[addresses]
lottery_addr="0xf4636011cb8b04c3e2c10ae013e76f977d3f746cf104f5785a9bde76bde7873f"
yield_addr="0x07261beac6e023ed2ba91de8e784c4ae66ef008e62c6ffd989410a7d344fa776"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.yield]
local = "../yield"

[dev-dependencies]
