[package]
name = "lottery"
version = "1.0.0"
authors = ["arjanjohan"]

[addresses]
lottery_addr="0x71eaeb8459fe5c2df571f45593e4b767a0a9288f8591fd50a254ba49b1887885"
yield_addr="0x07261beac6e023ed2ba91de8e784c4ae66ef008e62c6ffd989410a7d344fa776"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.yield]
local = "../yield"

[dev-dependencies]
