[package]
name = "yield_generating_protocol"
version = "1.0.0"
authors = ["arjanjohan"]

[addresses]
yield_addr="df921eb55ba53511bfe3c15823a66ab050bb97bf66b219d8c3f68111e2debf12"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
